// frontend/src/components/NoteCard.vue
<template>
  <div
    class="card cursor-pointer hover:shadow-md transition-shadow duration-150 flex overflow-hidden"
    @click="$emit('click', note.id)"
  >
    <!-- Color accent bar -->
    <div
      class="w-1 shrink-0 rounded-l-xl"
      :style="{ backgroundColor: category?.color ?? '#6B7280' }"
    />

    <div class="flex-1 p-4 min-w-0">
      <!-- Category badge + date -->
      <div class="flex items-center justify-between mb-2 gap-2">
        <CategoryBadge v-if="category" :category="category" />
        <span v-else class="text-xs text-gray-400">Uncategorised</span>
        <span class="text-xs text-gray-400 shrink-0">{{ relativeDate }}</span>
      </div>

      <!-- Title -->
      <h3 class="font-semibold text-gray-900 text-sm leading-tight mb-1 truncate">
        {{ note.title || 'Untitled' }}
      </h3>

      <!-- Preview -->
      <p class="text-xs text-gray-500 line-clamp-2 mb-2">
        {{ note.content_preview || 'No content' }}
      </p>

      <!-- Tags -->
      <div v-if="note.tags.length > 0" class="flex flex-wrap gap-1">
        <TagChip v-for="tag in visibleTags" :key="tag" :tag="tag" />
        <span v-if="note.tags.length > 4" class="text-xs text-gray-400 px-1">
          +{{ note.tags.length - 4 }} more
        </span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { NoteListItem } from '@/api/notes'
import type { Category } from '@/api/categories'
import CategoryBadge from './CategoryBadge.vue'
import TagChip from './TagChip.vue'

const props = defineProps<{
  note: NoteListItem
  category?: Category
}>()

defineEmits<{
  click: [id: string]
}>()

const visibleTags = computed(() => props.note.tags.slice(0, 4))

const relativeDate = computed(() => {
  const date = new Date(props.note.modified_at)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffSecs = Math.floor(diffMs / 1000)
  const diffMins = Math.floor(diffSecs / 60)
  const diffHours = Math.floor(diffMins / 60)
  const diffDays = Math.floor(diffHours / 24)

  if (diffSecs < 60) return 'Just now'
  if (diffMins < 60) return `${diffMins}m ago`
  if (diffHours < 24) return `${diffHours}h ago`
  if (diffDays === 1) return 'Yesterday'
  if (diffDays < 7) return `${diffDays} days ago`
  return date.toLocaleDateString()
})
</script>

// frontend/src/components/NoteCard.tsx
import { Pin, Globe, FolderInput } from 'lucide-react'
import type { NoteListItem } from '@/api/notes'
import type { Category } from '@/api/categories'
import CategoryBadge from './CategoryBadge'
import TagChip from './TagChip'

function relativeDate(dateStr: string): string {
  const date = new Date(dateStr)
  const diffMs = Date.now() - date.getTime()
  const diffSecs = Math.floor(diffMs / 1000)
  const diffMins = Math.floor(diffSecs / 60)
  const diffHours = Math.floor(diffMins / 60)
  const diffDays = Math.floor(diffHours / 24)
  if (diffSecs < 60) return 'Just now'
  if (diffMins < 60) return `${diffMins}m ago`
  if (diffHours < 24) return `${diffHours}h ago`
  if (diffDays === 1) return 'Yesterday'
  if (diffDays < 7) return `${diffDays} days ago`
  return date.toLocaleDateString()
}

const textShadow = '0 1px 4px rgba(0,0,0,0.6), 0 0 2px rgba(0,0,0,0.4)'

interface Props {
  note: NoteListItem
  category?: Category
  onClick: (id: string) => void
  onPin?: (id: string) => void
  onMove?: (id: string) => void
  viewMode?: 'list' | 'card'
}

export default function NoteCard({ note, category, onClick, onPin, onMove, viewMode = 'list' }: Props) {
  const visibleTags = note.tags.slice(0, 3)

  if (viewMode === 'card') {
    const hasImage = Boolean(note.first_image_url)
    return (
      <div
        className={`relative rounded-xl overflow-hidden cursor-pointer h-52 flex flex-col justify-between shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-200 ${
          hasImage
            ? 'border border-gray-200 dark:border-gray-700'
            : 'card'
        }`}
        onClick={() => onClick(note.id)}
      >
        {/* Background image — fixed blur independent of any active theme */}
        {hasImage && (
          <div
            className="absolute inset-0 bg-cover bg-center"
            style={{ backgroundImage: `url(${note.first_image_url})`, filter: 'blur(3px)', transform: 'scale(1.05)' }}
          />
        )}
        {/* Wash overlay for image cards only — note-card-img-wash suppresses
            backdrop-filter so the static image blur is not compounded by the
            theme glass blur. No-image cards use .card on the outer div instead. */}
        {hasImage && (
          <div className="absolute inset-0 note-card-img-wash bg-white/40 dark:bg-black/50" />
        )}

        {/* Category color accent when no image */}
        {!hasImage && (
          <div className="absolute top-0 left-0 right-0 h-1 rounded-t-xl" style={{ backgroundColor: category?.color ?? '#6B7280' }} />
        )}

        {/* Top row: category + time + pin */}
        <div className="relative z-10 flex items-center justify-between px-3 pt-3 gap-2">
          <div style={hasImage ? { filter: 'drop-shadow(0 1px 2px rgba(0,0,0,0.5))' } : undefined}>
            {category
              ? <CategoryBadge category={category} />
              : <span className="text-xs text-gray-400">Uncategorised</span>}
          </div>
          <div className="flex items-center gap-1.5 shrink-0">
            <span
              className="text-xs text-gray-500 dark:text-gray-400"
              style={hasImage ? { color: 'white', textShadow } : undefined}
            >
              {relativeDate(note.modified_at)}
            </span>
            {note.is_shared && (
              <span title="Shared publicly">
                <Globe
                  className="w-3.5 h-3.5 text-green-400"
                  style={hasImage ? { color: 'rgba(255,255,255,0.85)' } : undefined}
                />
              </span>
            )}
            {onMove && (
              <button
                className="p-0.5 rounded text-gray-300 hover:text-gray-500 transition-colors"
                style={hasImage ? { color: 'rgba(255,255,255,0.7)' } : undefined}
                title="Move to folder"
                onPointerDown={(e) => e.stopPropagation()}
                onClick={(e) => { e.stopPropagation(); onMove(note.id) }}
              >
                <FolderInput className="w-3.5 h-3.5" />
              </button>
            )}
            {onPin && (
              <button
                className={`p-0.5 rounded transition-colors ${note.is_pinned ? 'text-blue-400' : 'text-gray-300 hover:text-gray-500'}`}
                style={hasImage && !note.is_pinned ? { color: 'rgba(255,255,255,0.7)' } : undefined}
                title={note.is_pinned ? 'Unpin note' : 'Pin to top'}
                onPointerDown={(e) => e.stopPropagation()}
                onClick={(e) => { e.stopPropagation(); onPin(note.id) }}
              >
                <Pin className="w-3.5 h-3.5" fill={note.is_pinned ? 'currentColor' : 'none'} />
              </button>
            )}
          </div>
        </div>

        {/* Bottom: title + preview + tags */}
        <div className="relative z-10 px-3 pb-3">
          <h3
            className="font-semibold text-sm leading-tight mb-1 truncate text-gray-900 dark:text-gray-100"
            style={hasImage ? { color: 'white', textShadow } : undefined}
          >
            {note.title || 'Untitled'}
          </h3>
          <p
            className="text-xs text-gray-500 dark:text-gray-400 line-clamp-2 mb-1.5"
            style={hasImage ? { color: 'rgba(255,255,255,0.9)', textShadow } : undefined}
          >
            {note.content_preview || 'No content'}
          </p>
          {visibleTags.length > 0 && (
            <div className="flex flex-wrap gap-1">
              {visibleTags.map((tag) => (
                <span
                  key={tag}
                  className="text-xs px-1.5 py-0.5 rounded-full"
                  style={hasImage
                    ? { backgroundColor: 'rgba(255,255,255,0.25)', color: 'white', textShadow }
                    : { backgroundColor: 'rgba(0,0,0,0.06)', color: '#6b7280' }}
                >
                  #{tag}
                </span>
              ))}
              {note.tags.length > 3 && (
                <span
                  className="text-xs px-1"
                  style={hasImage ? { color: 'rgba(255,255,255,0.7)' } : { color: '#9ca3af' }}
                >
                  +{note.tags.length - 3}
                </span>
              )}
            </div>
          )}
        </div>
      </div>
    )
  }

  // List view
  return (
    <div
      className="card cursor-pointer flex overflow-hidden dark:bg-gray-800 dark:border-gray-700"
      onClick={() => onClick(note.id)}
    >
      <div className="w-1 shrink-0 rounded-l-xl" style={{ backgroundColor: category?.color ?? '#6B7280' }} />
      <div className="flex-1 p-4 min-w-0">
        <div className="flex items-center justify-between mb-2 gap-2">
          {category ? <CategoryBadge category={category} /> : <span className="text-xs text-gray-400">Uncategorised</span>}
          <div className="flex items-center gap-2 shrink-0">
            <span className="text-xs text-gray-400">{relativeDate(note.modified_at)}</span>
            {note.is_shared && (
              <span title="Shared publicly"><Globe className="w-3.5 h-3.5 text-green-400" /></span>
            )}
            {onMove && (
              <button
                className="p-0.5 rounded text-gray-300 hover:text-gray-500 transition-colors"
                title="Move to folder"
                onPointerDown={(e) => e.stopPropagation()}
                onClick={(e) => { e.stopPropagation(); onMove(note.id) }}
              >
                <FolderInput className="w-3.5 h-3.5" />
              </button>
            )}
            {onPin && (
              <button
                className={`p-0.5 rounded transition-colors ${note.is_pinned ? 'text-blue-500' : 'text-gray-300 hover:text-gray-500'}`}
                title={note.is_pinned ? 'Unpin note' : 'Pin to top'}
                onPointerDown={(e) => e.stopPropagation()}
                onClick={(e) => { e.stopPropagation(); onPin(note.id) }}
              >
                <Pin className="w-3.5 h-3.5" fill={note.is_pinned ? 'currentColor' : 'none'} />
              </button>
            )}
          </div>
        </div>
        <h3 className="font-semibold text-gray-900 dark:text-gray-100 text-sm leading-tight mb-1 truncate">
          {note.title || 'Untitled'}
        </h3>
        <p className="text-xs text-gray-500 dark:text-gray-400 line-clamp-2 mb-2">{note.content_preview || 'No content'}</p>
        {note.tags.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {note.tags.slice(0, 4).map((tag) => <TagChip key={tag} tag={tag} />)}
            {note.tags.length > 4 && <span className="text-xs text-gray-400 px-1">+{note.tags.length - 4} more</span>}
          </div>
        )}
      </div>
    </div>
  )
}
