// frontend/src/components/TagChip.vue
<template>
  <span
    class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs bg-gray-100 text-gray-700 border border-gray-200"
  >
    <span>#{{ tag }}</span>
    <button
      v-if="removable"
      class="ml-0.5 text-gray-400 hover:text-gray-600 focus:outline-none"
      :aria-label="`Remove tag ${tag}`"
      @click.stop="$emit('remove', tag)"
    >
      <svg class="w-3 h-3" viewBox="0 0 20 20" fill="currentColor">
        <path
          fill-rule="evenodd"
          d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
          clip-rule="evenodd"
        />
      </svg>
    </button>
  </span>
</template>

<script setup lang="ts">
defineProps<{
  tag: string
  removable?: boolean
}>()

defineEmits<{
  remove: [tag: string]
}>()
</script>

// frontend/src/components/TagChip.tsx
interface Props {
  tag: string
  removable?: boolean
  onRemove?: (tag: string) => void
}

export default function TagChip({ tag, removable, onRemove }: Props) {
  return (
    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs bg-gray-100 text-gray-700 border border-gray-200">
      <span>#{tag}</span>
      {removable && (
        <button
          className="ml-0.5 text-gray-400 hover:text-gray-600 focus:outline-none"
          aria-label={`Remove tag ${tag}`}
          onClick={(e) => { e.stopPropagation(); onRemove?.(tag) }}
        >
          <svg className="w-3 h-3" viewBox="0 0 20 20" fill="currentColor">
            <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
          </svg>
        </button>
      )}
    </span>
  )
}
